### ISSUE TITLE
Fix some bugs

### ISSUE THREAD

**Issue by hkhanna** [hkhanna/django-stripe-billing#6]
## Description
- If your card fails (eg its expired) and you update it in the Portal, it doesn’t automatically trigger a retry.
- If it does retry, the state is wonky. Basically you need to set the payment state to OK whenever a Renew Sub happens. Write a test for this.
- An attach then decline card (or perhaps any decline [UPDATE: its any attempt to submit a card. just creating the checkout session doesnt create a customer]) will create a new customer each time. So you’ll end up with dups if the customer doesn’t complete the workflow. This happens because we don’t actually store their `customer_id` until their signup is successful.
- I think fixing the immediately above bullet will allow me to test failed cards.
- Every Stripe Event should be attached to a user, even if its ultimately ignored. This will become a forcing function for events that come in where we don’t have a mathcing customer id, but we do have a matching email, that’s an opportunity to attach the customer_id.
- I think we should listen to `customer.created`, which is the first event fired in the workflow. That should store the customer id in the database. That means the `checkout.session.completed` event will only be confirmatory when checking `client_reference_id`.
- You can look at all of a Customer’s `events` to get a sense of which ones will be useful.

## Tasks
- [x] Use `invoice.paid` for new subscriptions. 
- [ ] Use `checkout.session.completed` only to confirm. 
- [x] Every event should be attached to a customer.
- [x] If an incoming event's customer ID can't be found, it should match based on email and fill in the customer id. 
- [ ] If an incoming event's customer ID is found, but the emails don't match, use the customer id but log an error.
- [x] When setting an event type, also set `primary`. 
- [x] Replace `IGNORE` with `UNKNOWN`. 
- [x] Whenever an UNKNOWN event is saved, log an error.
- [x] Fix tests
- [x] Add new tests
- [x] todos
- [ ] fix the issues above
- [ ] data migration

**Comment by hkhanna** [comment]
## Tests
- non-primary events should get the correct type but ultimately be ignored
- non-primary events should have a user attached

**Comment by hkhanna** [comment]
hand test incomplete -> fix flow
